services:

  # THE MAIN OPACA RUNTIME PLATFORM RUNNING IN DOCKER
  # (Agent Containers can run in the same Docker or somewhere else)
  opaca-platform:
    image: ghcr.io/gt-arc/opaca/opaca-platform:latest
    ports:
      - "8050:8000"
    # Environment variables with no value after ":" are taken from .env file
    environment:
      # General Settings; NOTE: PUBLIC_URL must be set for PLATFORM_ENVIRONMENT 'DOCKER'!
      PORT:
      PUBLIC_URL: http://host.docker.internal:8050
      CONTAINER_ENVIRONMENT:
      PLATFORM_ENVIRONMENT: DOCKER
      SESSION_POLICY:
      CONTAINER_TIMEOUT_SEC:
      DEFAULT_IMAGE_DIRECTORY:
      EVENT_HISTORY_SIZE:
      ALWAYS_PULL_IMAGES:
      # Security & Authentication
      ENABLE_AUTH:
      SECRET:
      PLATFORM_ADMIN_USER:
      PLATFORM_ADMIN_PWD:
      # User Management DB
      DB_EMBED: true
      DB_URI: mongodb://user:pass@opaca-platform-userdb:27017/admin
      DB_NAME: opaca-user-data
      # Image Registry Credentials
      REGISTRY_SEPARATOR:
      REGISTRY_NAMES:
      REGISTRY_LOGINS:
      REGISTRY_PASSWORDS:
      # Docker (only for CONTAINER_ENVIRONMENT: DOCKER)
      REMOTE_DOCKER_HOST:
      REMOTE_DOCKER_PORT:
      # Kubernetes (only for PLATFORM_ENVIRONMENT: KUBERNETES)
      KUBERNETES_NAMESPACE:
      KUBERNETES_CONFIG:
    # for running containers on the same Docker as the platform itself
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # FastAPI-based backend of SAGE
  opaca-llm-backend:
    build: ../Backend
    image: opaca-llm-backend
    ports:
      - "3001:3001"
    environment:
      OPENAI_API_KEY:
      ANTHROPIC_API_KEY:
      GEMINI_API_KEY:
      MISTRAL_API_KEY: